baseurl = "http://example.org/"
languageCode = "fr-CH"
title = "Hugo Cards"
theme = "hugo-cards"
paginate = 6

[params]
  builtBy = "bool"
  defaultImage = "gopher.jpg"

  facebook = "https://www.facebook.com/andrea.brandani.71"
  quora = ""
  twitter = "http://twitter.com/Andreanefer"
  github = "https://github.com/andreanefer"
  email = "andrea.brandani@heig-vd.ch"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  custom_css = ["css/custom.css"]

  [params.copyright]
     name = "bool"
     link = "https://bool.netlify.com"
